services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    # Override the production CMD from the Dockerfile for local development
    # Use uvicorn with --reload for hot-reloading
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      # Exclude node_modules from the volume to use the container's version
      - /app/node_modules
    environment:
      # Ensure the frontend can connect to the backend container
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000/ws
    # Override the production CMD to run the development server
    command: npm run dev

volumes:
  node_modules:
